In [1]:
import sys
sys.path.append('..')
import numpy as np
from common.layers import MatMul

In [3]:
text = 'you say goodbye and i say hello.'
text = text.lower()
text = text.replace('.', ' .')
print(text)
arr = text.split(' ')
print(arr)

you say goodbye and i say hello .
['you', 'say', 'goodbye', 'and', 'i', 'say', 'hello', '.']


In [8]:
id_to_word = {}
word_to_id = {}
for word in arr:
    if word not in word_to_id:
        newid = len(word_to_id)
        id_to_word[newid] = word
        word_to_id[word] = newid

print(id_to_word)
print(word_to_id)

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}
{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}


In [11]:
text_to_id = []
for word in arr:
    text_to_id.append(word_to_id[word])
print(text_to_id)

[0, 1, 2, 3, 4, 1, 5, 6]


In [27]:
window_size = 1
contexts=[]
target=[]

for i in range(window_size, len(text_to_id)-window_size):
    temp=[]
    for j in range(-window_size, window_size+1):        
        if j is not 0:            
            temp.append(text_to_id[i+j])
        else:
            target.append(text_to_id[i+j])
    contexts.append(temp)

print(contexts)
print(target)

target = np.array(target)
contexts = np.array(contexts)


[[0, 2], [1, 3], [2, 4], [3, 1], [4, 5], [1, 6]]
[1, 2, 3, 4, 1, 5]


In [28]:
for i in range(-1, 2):
    print(i)

-1
0
1


In [29]:
def convert_one_hot(corpus, vocab_size):
    '''원핫 표현으로 변환

    :param corpus: 단어 ID 목록(1차원 또는 2차원 넘파이 배열)
    :param vocab_size: 어휘 수
    :return: 원핫 표현(2차원 또는 3차원 넘파이 배열)
    '''
    N = corpus.shape[0]

    if corpus.ndim == 1:
        one_hot = np.zeros((N, vocab_size), dtype=np.int32)
        for idx, word_id in enumerate(corpus):
            one_hot[idx, word_id] = 1

    elif corpus.ndim == 2:
        C = corpus.shape[1]
        one_hot = np.zeros((N, C, vocab_size), dtype=np.int32)
        for idx_0, word_ids in enumerate(corpus):
            for idx_1, word_id in enumerate(word_ids):
                one_hot[idx_0, idx_1, word_id] = 1

    return one_hot

In [30]:
print(convert_one_hot(target, len(word_to_id)))

[[0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0]]
